=== jesuspv/ETLGen/etc/ETL.dtd
<!-- Configuracion -->
<!ELEMENT Configuracion (Generadores, Importaciones, Parametros)>
<!ELEMENT Generadores (asociar)+>
<!ATTLIST Generadores
	valor-nulo CDATA #IMPLIED
	prob-nulo  CDATA #IMPLIED
>
<!ELEMENT asociar EMPTY>
<!ATTLIST asociar
	elemento  CDATA #REQUIRED
	generador CDATA #REQUIRED
	ruta      CDATA #REQUIRED
>
<!ELEMENT Importaciones (ruta)+>
<!ELEMENT ruta (#PCDATA)>

<!ELEMENT Parametros (cabecera)>
<!ELEMENT cabecera EMPTY>

<!-- Tabla -->
<!ELEMENT Tabla (Columnas, Restricciones)>
<!ATTLIST Tabla
	sp-campos CDATA #IMPLIED
	sp-filas  CDATA #IMPLIED
>

<!ELEMENT Columnas (cte | int | real | char | con | dis | sp | ref | ajena)+>
<!ATTLIST Columnas
	delim  CDATA #IMPLIED
	maxtam CDATA #IMPLIED
>

<!ELEMENT Restricciones (candidata | unica | no-nulo)*>
<!ELEMENT candidata (columna)+>
<!ELEMENT unica     (columna)+>
<!ELEMENT no-nulo   (columna)+>
<!ELEMENT columna   (#PCDATA)>

<!-- Generadores -->
<!ELEMENT cte (#PCDATA)>
<!ATTLIST cte
	id    CDATA #IMPLIED
>
<!ELEMENT int EMPTY>
<!ATTLIST int
	id    CDATA   #IMPLIED
	min   NMTOKEN #IMPLIED
	max   NMTOKEN #IMPLIED
	paso  NMTOKEN #IMPLIED
>
<!ELEMENT real EMPTY>
<!ATTLIST real
	id     CDATA   #IMPLIED
	min    NMTOKEN #IMPLIED
	max    NMTOKEN #IMPLIED
	paso   NMTOKEN #IMPLIED
	escala NMTOKEN #IMPLIED
>
<!ELEMENT char EMPTY>
<!ATTLIST char
	id    CDATA   #IMPLIED
	tipo  (M | m) #IMPLIED
>
<!ELEMENT con (cte | entero | real | char | con | dis | sp | ajena)*>
<!ATTLIST con
	id    CDATA #IMPLIED
>
<!ELEMENT dis (cte | entero | real | char | con | dis | sp | ajena)*>
<!ATTLIST dis
	id    CDATA #IMPLIED
>
<!ELEMENT sp EMPTY>
<!ATTLIST sp
	id    CDATA #IMPLIED
	val   CDATA #IMPLIED
>
<!ELEMENT ref EMPTY>
<!ATTLIST ref
	id  CDATA #IMPLIED
	gen CDATA #REQUIRED
>
<!ELEMENT ajena EMPTY>
<!ATTLIST ajena
	tabla       CDATA #REQUIRED
	delim-colum CDATA #IMPLIED
	sp-colum    CDATA #IMPLIED
	sp-filas    CDATA #IMPLIED
	nom-colum   CDATA #IMPLIED
	num-colum   CDATA #IMPLIED
>

=== jesuspv/ETLGen/data/ciudad.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<ref id="CIU_ID" gen="ID" />
		<ref id="CIU_NOMBRE" gen="ciudad" />
		<ajena id="FK_CIUDAD_PROVINCIA" tabla="provincia" nom-colum="PROV_ID" />
	</Columnas>
	<Restricciones>
		<candidata><columna>CIU_NOMBRE</columna></candidata>
		<candidata><columna>CIU_ID</columna></candidata>
		<no-nulo><columna>FK_CIUDAD_PROVINCIA</columna></no-nulo>
	</Restricciones>
</Tabla>

=== jesuspv/ETLGen/lib/descripcion.xml
<?xml version="1.0"?>
<!DOCTYPE Columnas SYSTEM "etc/ETL.dtd">
<Columnas>
	<dis id="descripcion">
		<cte>Es grande y bonito</cte>
		<cte>Tiene muchas cosas</cte>
		<cte>Esta me gusta pero es mejor aquella</cte>
		<cte>No esta mal, pero las hay mejores</cte>
		<cte>La ultima reforma fue dolorosa</cte>
		<cte>Aplicado y profesional</cte>
		<cte>Uno de los mejores</cte>
		<cte>Debe mejorar</cte>
		<cte>Progresa adecuadamente</cte>
	</dis>
</Columnas>

=== jesuspv/ETLGen/data/libro.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<int id="LIB_ANYO_PUBLICACION" min="1900" max="2004" paso="1" />
		<ref id="LIB_AUTOR_SECUNDARIO_1" gen="persona" />
		<ref id="LIB_AUTOR_SECUNDARIO_2" gen="persona" />
		<ref id="LIB_BIBLIOGRAFIA_RECOMENDADA" gen="bool" />
		<ref id="LIB_CD" gen="bool" />
		<int id="LIB_CDU_1" min="100000" max="999999" paso="1" />
		<int id="LIB_CDU_2" min="100000" max="999999" paso="1" />
		<int id="LIB_DEPOSITO_LEGAL" min="100000" max="999999" paso="1" />
		<con id="LIB_DIMENSIONES">
			<int min="20" max="500" paso="5" />
			<cte>x</cte>
			<int min="20" max="300" paso="5" />
			<cte>x</cte>
			<int min="10" max="100" paso="2" />
		</con>
		<ref id="LIB_EDITORIAL" gen="persona-apellido" />
		<ref id="LIB_GRAFICOS" gen="bool" />
		<ref id="LIB_ID" gen="ID" />
		<dis id="LIB_IDIOMA">
			<cte>Español</cte>
			<cte>Español</cte>
			<cte>Ingles</cte>
			<cte>Frances</cte>
			<cte>Italiano</cte>
			<cte>Aleman</cte>
			<cte>Japones</cte>
		</dis>
		<int id="LIB_ISBN" min="100000" max="999999" paso="1" />
		<dis id="LIB_LUGAR_PUBLICACION">
			<cte>España</cte>
			<cte>Inglaterra</cte>
			<cte>EEUU</cte>
			<cte>Alemania</cte>
			<cte>Italia</cte>
			<cte>Francia</cte>
			<cte>Holanda</cte>
			<cte>Japon</cte>
		</dis>
		<ref id="LIB_MATERIA_1" gen="area" />
		<ref id="LIB_MATERIA_2" gen="area" />
		<ref id="LIB_MATERIA_3" gen="area" />
		<ref id="LIB_MATERIA_4" gen="area" />
		<ref id="LIB_NOTA_GENERAL" gen="descripcion" />
		<int id="LIB_NUM_AUTORES" min="1" max="10" paso="1" />
		<int id="LIB_NUM_CAPITULOS" min="1" max="100" paso="1" />
		<int id="LIB_NUM_EJEMPLARES" min="100" max="10000" paso="1" />
		<int id="LIB_NUM_PAGINAS" min="100" max="1000" paso="5" />
		<con id="LIB_SERIE">
				<char tipo="M" />
				<char tipo="M" />
				<char tipo="M" />
				<char tipo="M" />
		</con>
		<con id="LIB_SIGNATURA">
				<char tipo="M" />
				<char tipo="M" />
				<char tipo="M" />
				<char tipo="M" />
		</con>
		<ref id="LIB_TIPO" gen="area" />
		<ref id="LIB_TITULO" gen="asignatura" />
		<ajena id="FK_LIBRO_BIBLIOTECA" tabla="biblioteca" nom-colum="BIB_ID" />
		<ajena id="FK_LIBRO_AUTOR" tabla="autor" nom-colum="AUT_ID" />
	</Columnas>
	<Restricciones>
		<candidata><columna>LIB_ISBN</columna></candidata>
		<candidata><columna>LIB_ID</columna></candidata>
		<no-nulo><columna>FK_LIBRO_BIBLIOTECA</columna></no-nulo>
		<no-nulo><columna>FK_LIBRO_AUTOR</columna></no-nulo>
	</Restricciones>
</Tabla>

=== jesuspv/ETLGen/data/abstencion.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<ajena id="FK_ASIGNATURA" tabla="asignatura" nom-colum="ASI_ID" />
		<da_smart_key id="FK_FECHA" file="C:\bdm\etlgen\ora\da_smart_key.txt" />
		<ajena id="FK_EXAMEN" tabla="examen" nom-colum="EXA_ID" />
		<ajena id="FK_ALUMNO" tabla="matricula" nom-colum="MAT_ID" />
		<cte id="DUMMY">1</cte>
	</Columnas>
	<Restricciones>
		<candidata><columna>FK_ASIGNATURA</columna>
		           <columna>FK_FECHA</columna>
		           <columna>FK_EXAMEN</columna>
		           <columna>FK_ALUMNO</columna>
		</candidata>
		<no-nulo><columna>DUMMY</columna></no-nulo>
	</Restricciones>
</Tabla>

=== jesuspv/ETLGen/data/carrera.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<int id="CAR_ANYOS_ACADEMICOS_CICLO_1" min="1" max="5" paso="1" />
		<int id="CAR_ANYOS_ACADEMICOS_CICLO_2" min="1" max="5" paso="1" />
		<int id="CAR_ANYO_IMPLANTACION" min="1995" max="2004" paso="1" />
		<int id="CAR_ANYO_PLAN_SUSTITUIDO" min="1980" max="2004" paso="1" />
		<int id="CAR_CARGA_LECTIVA_TOTAL" min="100" max="500" paso="5" />
		<dis id="CAR_CENTRO_RESPONSABLE_CODIGO">
			<cte>EPS</cte>
		</dis>
		<dis id="CAR_CENTRO_RESPONSABLE_NOMBRE">
			<cte>Escuela Politecnica Superior</cte>
		</dis>
		<int id="CAR_CICLO" min="1" max="2" paso="1" />
		<dis id="CAR_CODIGO">
			<con>
				<char tipo="M" />
				<char tipo="M" />
				<char tipo="M" />
			</con>
		</dis>
		<int id="CAR_CREDITOS_ANYO_1" min="30" max="99" paso="1" />
		<int id="CAR_CREDITOS_ANYO_2" min="30" max="99" paso="1" />
		<int id="CAR_CREDITOS_ANYO_3" min="30" max="99" paso="1" />
		<int id="CAR_CREDITOS_ANYO_4" min="30" max="99" paso="1" />
		<int id="CAR_CREDITOS_ANYO_5" min="30" max="99" paso="1" />
		<ref id="CAR_CREDITOS_PRACTI" gen="bool" />
		<int id="CAR_CREDITOS_PR1" min="15" max="60" paso="1" />
		<int id="CAR_CREDITOS_PR2" min="15" max="60" paso="1" />
		<int id="CAR_CREDITOS_PR3" min="15" max="60" paso="1" />
		<int id="CAR_CREDITOS_PR4" min="15" max="60" paso="1" />
		<int id="CAR_CREDITOS_PR5" min="15" max="60" paso="1" />
		<int id="CAR_CREDITOS_TEO1" min="15" max="60" paso="1" />
		<int id="CAR_CREDITOS_TEO2" min="15" max="60" paso="1" />
		<int id="CAR_CREDITOS_TEO3" min="15" max="60" paso="1" />
		<int id="CAR_CREDITOS_TEO4" min="15" max="60" paso="1" />
		<int id="CAR_CREDITOS_TEO5" min="15" max="60" paso="1" />
		<ref id="CAR_CREDITOS_TRABAJOS" gen="bool" />
		<ref id="CAR_DESCRIPCION" gen="descripcion" />
		<ref id="CAR_ID" gen="ID" />
		<ref id="CAR_NOMBRE" gen="carrera" />
		<con id="CAR_PLAN_SUSTITUIDO">
			<ref gen="carrera" />
			<int min="1980" max="2004" paso="1" />
		</con>
		<ref id="CAR_PROYECTO_FIN_CAR" gen="bool" />
		<ajena id="FK_CARRERA_DOCTORADO" tabla="doctorado" nom-colum="DOC_ID" />
		<ajena id="FK_CARRERA_AREA" tabla="area" nom-colum="AREA_ID" />
	</Columnas>
	<Restricciones>
		<candidata><columna>CAR_CODIGO</columna></candidata>
		<candidata><columna>CAR_ID</columna></candidata>
		<no-nulo><columna>FK_CARRERA_AREA</columna></no-nulo>
		<no-nulo><columna>FK_CARRERA_DOCTORADO</columna></no-nulo>
	</Restricciones>
</Tabla>

=== jesuspv/ETLGen/data/asignatura.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<con id="ASI_CODIGO">
				<char tipo="M" />
				<char tipo="M" />
				<char tipo="M" />
		</con>
		<ref id="ASI_COORDINADOR" gen="persona" />
		<real id="ASI_CREDITOS_PRACT" min="1.0" max="8.0" escala="2" paso="0.5" />
		<real id="ASI_CREDITOS_TEO" min="1.0" max="8.0" escala="2" paso="0.5" />
		<ref id="ASI_DESCRIPCION" gen="descripcion" />
		<ref id="ASI_DIRECCION_WEB" gen="web" />
		<ref id="ASI_ID" gen="ID" />
		<con id="ASI_INCOMPATIBLE1">
				<char tipo="M" />
				<char tipo="M" />
				<char tipo="M" />
		</con>
		<con id="ASI_INCOMPATIBLE2">
				<char tipo="M" />
				<char tipo="M" />
				<char tipo="M" />
		</con>
		<con id="ASI_INCOMPATIBLE3">
				<char tipo="M" />
				<char tipo="M" />
				<char tipo="M" />
		</con>
		<con id="ASI_INCOMPATIBLE4">
				<char tipo="M" />
				<char tipo="M" />
				<char tipo="M" />
		</con>
		<ref id="ASI_METODO_DOCENTE" gen="descripcion" />
		<ref id="ASI_NOMBRE" gen="asignatura" />
		<int id="ASI_NUM_EXAMENES_PREVISTOS" min="1" max="10" paso="1" />
		<int id="ASI_NUM_INCOMPATIBLES" min="1" max="10" paso="1" />
		<int id="ASI_NUM_PRERREQUISITOS" min="1" max="10" paso="1" />
		<int id="ASI_NUM_RECOMENDACIOES" min="1" max="10" paso="1" />
		<int id="ASI_NUM_TEMAS" min="1" max="50" paso="1" />
		<ref id="ASI_OBJETIVOS" gen="descripcion" />
		<ref id="ASI_OFERTADA_LE" gen="bool" />
		<ref id="ASI_PRERREQUISITO1" gen="asignatura" />
		<ref id="ASI_PRERREQUISITO2" gen="asignatura" />
		<ref id="ASI_PRERREQUISITO3" gen="asignatura" />
		<ref id="ASI_PRERREQUISITO4" gen="asignatura" />
		<ref id="ASI_RECOMENDACION1" gen="asignatura" />
		<ref id="ASI_RECOMENDACION2" gen="asignatura" />
		<ref id="ASI_RECOMENDACION3" gen="asignatura" />
		<ref id="ASI_RECOMENDACION4" gen="asignatura" />
		<dis id="ASI_TIPO_EXAMENES_EVALUACION">
			<cte>Examen Final</cte>
			<cte>Examenes Parciales</cte>
		</dis>
		<dis id="ASI_TIPO_PRACTICAS">
			<cte>Laboratorios</cte>
			<cte>Laboratorios</cte>
			<cte>Laboratorios</cte>
			<cte>Aularios</cte>
		</dis>
		<ajena id="FK_ASIGNATURA_DEPARTAMENTO" tabla="area" nom-colum="AREA_ID" />
		<ajena id="FK_ASIGNATURA_CARRERA" tabla="carrera" nom-colum="CAR_ID" />
	</Columnas>
	<Restricciones>
		<candidata><columna>ASI_CODIGO</columna></candidata>
		<candidata><columna>ASI_ID</columna></candidata>
		<no-nulo><columna>FK_ASIGNATURA_CARRERA</columna></no-nulo>
		<no-nulo><columna>FK_ASIGNATURA_DEPARTAMENTO</columna></no-nulo>
	</Restricciones>
</Tabla>

=== jesuspv/ETLGen/data/evaluacion.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<ajena id="FK_ALUMNO" tabla="matricula" nom-colum="MAT_ID" />
		<ajena id="FK_ASIGNATURA" tabla="asignatura" nom-colum="ASI_ID" />
		<ajena id="FK_EXAMEN" tabla="examen" nom-colum="EXA_ID" />
		<da_smart_key id="FK_FECHA" file="C:\bdm\etlgen\ora\da_smart_key.txt" />
		<ajena id="FK_PROFESOR" tabla="profesor" nom-colum="PRO_ID" />
		<real id="NOTA_NUMERICA" min="0.0" max="10.0" escala="2" paso="0.25" />
		<int id="NUM_CONVOCATORIA" min="1" max="6" paso="1" />
		<int id="NUM_HORAS_ESTUDIADAS" min="1" max="50" paso="5" />
		<int id="NUM_LIBROS_LEIDOS" min="0" max="20" paso="1" />
		<int id="PCENT_PREGUNTAS_CERO" min="0" max="60" paso="1" />
		<int id="PCENT_PREGUNTAS_PERFECTAS" min="10" max="50" paso="1" />
		<int id="PCENT_PREGUNTAS_PUNTUACION_MAX" min="0" max="100" paso="1" />
		<int id="PCENT_PREGUNTAS_PUNTUACION_MIN" min="0" max="100" paso="1" />
		<int id="PCENT_PREGUNTAS_VACIAS" min="0" max="30" paso="1" />
		<real id="PUNTUACION_AVG_EJERCICIO" min="0.3" max="0.7" escala="2" paso="0.025" />
		<real id="PUNTUACION_MAX_EJERCICIO" min="0.6" max="1.0" escala="2" paso="0.025" />
		<real id="PUNTUACION_MED_EJERCICIO" min="0.3" max="1.0" escala="2" paso="0.025" />
		<real id="PUNTUACION_MIN_EJERCICIO" min="0.0" max="0.3" escala="2" paso="0.025" />
		<real id="PUNTUACION_VAR_EJERCICIO" min="0.3" max="0.7" escala="2" paso="0.025" />
	</Columnas>
	<Restricciones>
		<candidata><columna>FK_ALUMNO</columna>
		           <columna>FK_ASIGNATURA</columna>
		           <columna>FK_EXAMEN</columna>
		           <columna>FK_FECHA</columna>
		           <columna>FK_PROFESOR</columna>
		</candidata>
	</Restricciones>
</Tabla>

=== jesuspv/ETLGen/lib/religion.xml
<?xml version="1.0"?>
<!DOCTYPE Columnas SYSTEM "etc/ETL.dtd">
<Columnas>
	<dis id="religion">
		<cte>Cristiana</cte>
		<cte>Cristiana</cte>
		<cte>Cristiana</cte>
		<cte>Ortodoxa</cte>
		<cte>Arabe</cte>
		<cte>Budismo</cte>
	</dis>
</Columnas>
