=== jesuspv/ETLGen/etc/ETL.dtd
<!-- Configuracion -->
<!ELEMENT Configuracion (Generadores, Importaciones, Parametros)>
<!ELEMENT Generadores (asociar)+>
<!ATTLIST Generadores
	valor-nulo CDATA #IMPLIED
	prob-nulo  CDATA #IMPLIED
>
<!ELEMENT asociar EMPTY>
<!ATTLIST asociar
	elemento  CDATA #REQUIRED
	generador CDATA #REQUIRED
	ruta      CDATA #REQUIRED
>
<!ELEMENT Importaciones (ruta)+>
<!ELEMENT ruta (#PCDATA)>

<!ELEMENT Parametros (cabecera)>
<!ELEMENT cabecera EMPTY>

<!-- Tabla -->
<!ELEMENT Tabla (Columnas, Restricciones)>
<!ATTLIST Tabla
	sp-campos CDATA #IMPLIED
	sp-filas  CDATA #IMPLIED
>

<!ELEMENT Columnas (cte | int | real | char | con | dis | sp | ref | ajena)+>
<!ATTLIST Columnas
	delim  CDATA #IMPLIED
	maxtam CDATA #IMPLIED
>

<!ELEMENT Restricciones (candidata | unica | no-nulo)*>
<!ELEMENT candidata (columna)+>
<!ELEMENT unica     (columna)+>
<!ELEMENT no-nulo   (columna)+>
<!ELEMENT columna   (#PCDATA)>

<!-- Generadores -->
<!ELEMENT cte (#PCDATA)>
<!ATTLIST cte
	id    CDATA #IMPLIED
>
<!ELEMENT int EMPTY>
<!ATTLIST int
	id    CDATA   #IMPLIED
	min   NMTOKEN #IMPLIED
	max   NMTOKEN #IMPLIED
	paso  NMTOKEN #IMPLIED
>
<!ELEMENT real EMPTY>
<!ATTLIST real
	id     CDATA   #IMPLIED
	min    NMTOKEN #IMPLIED
	max    NMTOKEN #IMPLIED
	paso   NMTOKEN #IMPLIED
	escala NMTOKEN #IMPLIED
>
<!ELEMENT char EMPTY>
<!ATTLIST char
	id    CDATA   #IMPLIED
	tipo  (M | m) #IMPLIED
>
<!ELEMENT con (cte | entero | real | char | con | dis | sp | ajena)*>
<!ATTLIST con
	id    CDATA #IMPLIED
>
<!ELEMENT dis (cte | entero | real | char | con | dis | sp | ajena)*>
<!ATTLIST dis
	id    CDATA #IMPLIED
>
<!ELEMENT sp EMPTY>
<!ATTLIST sp
	id    CDATA #IMPLIED
	val   CDATA #IMPLIED
>
<!ELEMENT ref EMPTY>
<!ATTLIST ref
	id  CDATA #IMPLIED
	gen CDATA #REQUIRED
>
<!ELEMENT ajena EMPTY>
<!ATTLIST ajena
	tabla       CDATA #REQUIRED
	delim-colum CDATA #IMPLIED
	sp-colum    CDATA #IMPLIED
	sp-filas    CDATA #IMPLIED
	nom-colum   CDATA #IMPLIED
	num-colum   CDATA #IMPLIED
>

=== jesuspv/ETLGen/lib/calle.xml
<?xml version="1.0"?>
<!DOCTYPE Columnas SYSTEM "etc/ETL.dtd">
<Columnas>
	<dis id="calle">
		<cte>Aneto, Calle  3F</cte>  
		<cte>Anís, Calle del  5C</cte>  
		<cte>Antonio Buero Vallejo, 3C</cte>  
		<cte>Antonio Gala, Plaza de  3B</cte>  
		<cte>Antonio López, 3C</cte>
		<cte>Añil, Calle  6C</cte>  
		<cte>Aralar, Calle  4F</cte>  
		<cte>Canela, Calle de la 4C</cte> 
		<cte>Canencia, Calle 3F</cte> 
		<cte>Canteros, 2C</cte> 
		<cte>Caños, Travesía de los 2D</cte>
		<cte>Caracas, Calle de 5C</cte> 
		<cte>Carmen Conde, Calle de 4C</cte> 
		<cte>Carmesí, Plaza 5C</cte> 
		<cte>Carrizal, Paseo del 2</cte>
		<cte>Cartero Rural, Plaza del 3B</cte> 
		<cte>Celeste, Plaza  5C</cte>
		<cte>Central, Parque 3C, 3D</cte>
		<cte>Central, Plaza 5B</cte> 
		<cte>Centro-1, Residencial 5B</cte> 
		<cte>Los Leones, Calle 3E</cte> 
		<cte>Luna, Ronda de la 5B</cte> 
		<cte>Luna, Travesía de la 4B</cte> 
		<cte>Luna, Plaza de la 4C</cte> 
		<cte>Luz, Avenida de la 4C</cte> 
		<cte>Naranjo, Calle  2F</cte> 
		<cte>Navacerrada, Calle de  2G</cte> 
		<cte>Navalcaballo, 7D</cte> 
		<cte>Neptuno, Calle de  5D</cte> 
		<cte>Niebla, Calle de la  5B</cte> 
		<cte>Nieve, Calle de la  5B</cte> 
		<cte>Perdiz, Calle de la  8C</cte> 
		<cte>Pico de San Pedro, Calle  1C</cte> 
		<cte>Pico, Calle del 3C</cte>  
		<cte>Piedrafita, Calle  2F</cte> 
		<cte>Pimienta, Calle de la  4D</cte> 
		<cte>Pintores, Sector  3C</cte> 
		<cte>Piqueras, Calle  3F</cte> 
		<cte>Planetas, Sector  5D</cte> 
		<cte>Plomada, Plaza de la  5E</cte> 
		<cte>Poniente, Ronda de  4A</cte> 
		<cte>Poniente, Travesía de  4B</cte> 
		<cte>Pueblos, Sector 2B</cte> 
	</dis>
</Columnas>

=== jesuspv/ETLGen/data/colegioCOU.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<ref id="COLC_DESCRIPCION" gen="descripcion" />
		<ref id="COLC_DIRECCION" gen="calle" />
		<ref id="COLC_ID" gen="ID" />
		<con id="COLC_NOMBRE">
			<ref gen="persona-nombre" />
			<sp />
			<ref gen="persona-apellido" />
		</con>
		<int id="COLC_NUM_ALUMNOS" min="50" max="1000" paso="10" />
		<ref id="COLC_SUBVENCIONADO" gen="bool" />
		<dis id="COLC_TIPO">
			<cte>Privado</cte>
			<cte>Publico</cte>
			<cte>Publico</cte>
			<cte>Publico</cte>
		</dis>
		<ajena id="FK_COLEGIOCOU_CIUDAD" tabla="ciudad" nom-colum="CIU_ID" />
	</Columnas>
	<Restricciones>
		<candidata><columna>COLC_NOMBRE</columna></candidata>
		<candidata><columna>COLC_ID</columna></candidata>
		<no-nulo><columna>FK_COLEGIOCOU_CIUDAD</columna></no-nulo>
	</Restricciones>
</Tabla>

=== jesuspv/ETLGen/data/doctorado.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<ref id="DOC_ID" gen="ID" />
		<ref id="DOC_AREA" gen="area" />
		<con id="DOC_CODIGO">
				<char tipo="M" />
				<char tipo="M" />
				<char tipo="M" />
				<ref gen="int2" />
		</con>
		<ref id="DOC_DEPARTAMENTO" gen="departamento" />
		<ref id="DOC_FECHA_FIN" gen="fecha" />
		<ref id="DOC_FECHA_INICIO" gen="fecha" />
		<ref id="DOC_NOMBRE" gen="asignatura" />
		<dis id="DOC_UNIVERSIDAD">
			<cte>Universidad de Alicante</cte>
			<cte>Universidad de Alicante</cte>
			<cte>Universidad de Alicante</cte>
			<cte>Universidad de Alicante</cte>
			<cte>Universidad de Valencia</cte>
			<cte>Universidad de Madrid</cte>
			<cte>Universidad de Malaga</cte>
			<cte>Universidad de Compostela</cte>
			<cte>Universidad de Granada</cte>
		</dis>
	</Columnas>
	<Restricciones>
		<candidata><columna>DOC_CODIGO</columna></candidata>
		<candidata><columna>DOC_ID</columna></candidata>
	</Restricciones>
</Tabla>

=== jesuspv/ETLGen/lib/departamento.xml
<?xml version="1.0"?>
<!DOCTYPE Columnas SYSTEM "etc/ETL.dtd">
<Columnas>
	<dis id="departamento">
		<cte>CONSTRUCCIONES ARQUITECTONICAS</cte>
		<cte>CIENCIA DE LA COMPUTACION E INT. ARTIF.</cte>
		<cte>EXPRESION GRAFICA Y CARTOGRAFIA</cte>
		<cte>FILOLOGIA INGLESA</cte>
		<cte>FISICA, INGENIERIA DE SISTEMAS Y TEORIA.</cte>
		<cte>GEOGRAFIA HUMANA</cte>
		<cte>INGENIERIA DE LA CONSTR.,OBRAS PUBL. E</cte>
		<cte>LENGUAJES Y SISTEMAS INFORMATICOS</cte>
		<cte>MATEMATICA APLICADA</cte>
		<cte>TECNOLOGIA INFORMATICA Y COMPUTACION</cte>
		<cte>ECONOMIA FINANCIERA, CONTABILIDAD Y MARK</cte>
	</dis>
</Columnas>

=== jesuspv/ETLGen/data/colegioFP.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<ref id="COLF_DESCRIPCION" gen="descripcion" />
		<ref id="COLF_DIRECCION" gen="calle" />
		<ref id="COLF_ID" gen="ID" />
		<con id="COLF_NOMBRE">
			<ref gen="persona-nombre" />
			<sp />
			<ref gen="persona-apellido" />
		</con>
		<int id="COLF_NUM_ALUMNOS" min="50" max="1000" paso="10" />
		<ref id="COLF_SUBVENCIONADO" gen="bool" />
		<dis id="COLF_TIPO">
			<cte>Privado</cte>
			<cte>Publico</cte>
			<cte>Publico</cte>
			<cte>Publico</cte>
		</dis>
		<ajena id="FK_COLEGIOFP_CIUDAD" tabla="ciudad" nom-colum="CIU_ID" />
	</Columnas>
	<Restricciones>
		<candidata><columna>COLF_NOMBRE</columna></candidata>
		<candidata><columna>COLF_ID</columna></candidata>
		<no-nulo><columna>FK_COLEGIOFP_CIUDAD</columna></no-nulo>
	</Restricciones>
</Tabla>

=== jesuspv/ETLGen/data/matricula.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<int id="MAT_CICLO" min="1" max="2" paso="1" />
		<int id="MAT_CURSO" min="1" max="5" paso="1" />
		<ref id="MAT_CURSO_ACADEMICO" gen="curso" />
		<dis id="MAT_ENTIDAD_BANCARIA">
			<cte>CAM</cte>
			<cte>La caixa</cte>
			<cte>Bancaja</cte>
			<cte>BBVA</cte>
		</dis>
		<ref id="MAT_FECHA_MATRICULA" gen="fecha" />
		<ref id="MAT_ID" gen="ID" />
		<ref id="MAT_NOTA_LIT_CURSO_ANT" gen="nota" />
		<real id="MAT_NOTA_NUM_CURSO_ANT" min="1.0" max="10.0" escala="2" paso="0.5" />
		<int id="MAT_NUMERO" min="10000000" max="99999999" paso="1" />
		<int id="MAT_NUM_APROBADOS_ANT" min="1" max="10" paso="1" />
		<int id="MAT_NUM_ASIG" min="1" max="10" paso="1" />
		<int id="MAT_NUM_ASIG_CUARTA" min="1" max="5" paso="1" />
		<int id="MAT_NUM_ASIG_LE_" min="1" max="10" paso="1" />
		<int id="MAT_NUM_ASIG_NO_PRIMERA" min="1" max="10" paso="1" />
		<int id="MAT_NUM_ASIG_OBL" min="1" max="10" paso="1" />
		<int id="MAT_NUM_ASIG_OPT" min="1" max="10" paso="1" />
		<int id="MAT_NUM_ASIG_PRIMERA" min="1" max="10" paso="1" />
		<int id="MAT_NUM_ASIG_QUINTA" min="1" max="10" paso="1" />
		<int id="MAT_NUM_ASIG_SEGUNDA" min="1" max="10" paso="1" />
		<int id="MAT_NUM_ASIG_TERCERA" min="1" max="10" paso="1" />
		<int id="MAT_NUM_ASIG_TRO" min="1" max="10" paso="1" />
		<real id="MAT_NUM_CREDITOS" min="20.0" max="80.0" escala="2" paso="0.5" />
		<real id="MAT_NUM_CRED_LE" min="2.0" max="50.0" escala="2" paso="0.5" />
		<real id="MAT_NUM_CRED_OBL" min="2.0" max="50.0" escala="2" paso="0.5" />
		<real id="MAT_NUM_CRED_OPT" min="2.0" max="50.0" escala="2" paso="0.5" />
		<real id="MAT_NUM_CRED_TRO" min="2.0" max="50.0" escala="2" paso="0.5" />
		<int id="MAT_NUM_MH_ANT" min="1" max="10" paso="1" />
		<int id="MAT_NUM_SUSPENSOS_ANT" min="1" max="10" paso="1" />
		<real id="MAT_PRECIO_MATRICULA" min="6.0" max="20.0" escala="2" paso="0.5" />
		<real id="MAT_PRECIO_MEDIO_ASIG" min="20.0" max="60.0" escala="2" paso="0.5" />
		<real id="MAT_PRECIO_MEDIO_CREDITO" min="6.0" max="20.0" escala="2" paso="0.5" />
		<dis id="MAT_TARGETA_CREDITO">
			<cte>VISA</cte>
			<cte>Carnet Jove</cte>
			<cte>Euromaster</cte>
			<cte>VISA ORO</cte>
		</dis>
		<ajena id="FK_MATRICULA_EXPEDIENTE" tabla="expediente" nom-colum="EXP_ID" />
	</Columnas>
	<Restricciones>
		<candidata><columna>MAT_NUMERO</columna></candidata>
		<candidata><columna>MAT_ID</columna></candidata>
		<no-nulo><columna>FK_MATRICULA_EXPEDIENTE</columna></no-nulo>
	</Restricciones>
</Tabla>

=== jesuspv/ETLGen/lib/ciudad.xml
<?xml version="1.0"?>
<!DOCTYPE Columnas SYSTEM "etc/ETL.dtd">
<Columnas>
	<dis id="ciudad">
		<cte>Vitoria</cte> 
		<cte>Albacete</cte> 
		<cte>Alicante</cte> 
		<cte>Almería</cte> 
		<cte>Oviedo</cte> 
		<cte>Ávila</cte> 
		<cte>Badajoz</cte> 
		<cte>Palma de Mallorca</cte> 
		<cte>Barcelona</cte> 
		<cte>Burgos</cte> 
		<cte>Cáceres</cte> 
		<cte>Cádiz</cte> 
		<cte>Santander</cte> 
		<cte>Castellón de la Plana</cte> 
		<cte>Ciudad Real</cte> 
		<cte>Córdoba</cte> 
		<cte>La Coruña</cte> 
		<cte>Cuenca</cte> 
		<cte>Gerona</cte> 
		<cte>Granada</cte> 
		<cte>Guadalajara</cte> 
		<cte>San Sebastián</cte> 
		<cte>Huelva</cte> 
		<cte>Huesca</cte> 
		<cte>Jaén</cte> 
		<cte>Logroño</cte>
		<cte>León</cte> 
		<cte>Lérida</cte> 
		<cte>Lugo</cte> 
		<cte>Madrid</cte> 
		<cte>Málaga</cte> 
		<cte>Murcia</cte> 
		<cte>Pamplona</cte> 
		<cte>Orense</cte> 
		<cte>Palencia</cte> 
		<cte>Las Palmas de Gran Canaria</cte> 
		<cte>Pontevedra</cte> 
		<cte>Salamanca</cte> 
		<cte>Santa Cruz de Tenerife</cte>
		<cte>Segovia</cte> 
		<cte>Sevilla</cte> 
		<cte>Soria</cte> 
		<cte>Tarragona</cte> 
		<cte>Teruel</cte> 
		<cte>Toledo</cte> 
		<cte>Valencia</cte> 
		<cte>Valladolid</cte> 
		<cte>Bilbao</cte> 
		<cte>Zamora</cte> 
		<cte>Zaragoza</cte>
	</dis>
</Columnas>

=== jesuspv/ETLGen/data/edificio.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<real id="EDI_ALTURA_PLANTA" min="2.0" max="10.0" paso="0.5" />
		<con id="EDI_CODIGO">
				<char tipo="M" />
				<char tipo="M" />
				<char tipo="M" />
				<int min="1" max="9" paso="1" />
		</con>
		<ref id="EDI_DESCRIPCION" gen="descripcion" />
		<int id="EDI_DISTANCIA_BIBLIO_ESPECIAL" min="10" max="1000" paso="10" />
		<int id="EDI_DISTANCIA_BIBLIO_GENERAL" min="10" max="1000" paso="10" />
		<int id="EDI_DISTANCIA_CLUB_SOCIAL" min="10" max="1000" paso="10" />
		<ref id="EDI_FECHA_CONSTRUCCION" gen="fecha" />
		<ref id="EDI_ID" gen="ID" />
		<ref id="EDI_NOMBRE" gen="edificio" />
		<int id="EDI_NUM_AULAS" min="10" max="50" paso="5" />
		<int id="EDI_NUM_PLANTAS" min="0" max="5" paso="1" />
		<dis id="EDI_ZONA_CAMPUS">
			<cte>Norte</cte>
			<cte>Sur</cte>
			<cte>Este</cte>
			<cte>Oeste</cte>
			<cte>Centro</cte>
		</dis>
	</Columnas>
	<Restricciones>
		<candidata><columna>EDI_CODIGO</columna></candidata>
		<candidata><columna>EDI_ID</columna></candidata>
	</Restricciones>
</Tabla>
