=== jesuspv/ETLGen/etc/ETL.dtd
<!-- Configuracion -->
<!ELEMENT Configuracion (Generadores, Importaciones, Parametros)>
<!ELEMENT Generadores (asociar)+>
<!ATTLIST Generadores
	valor-nulo CDATA #IMPLIED
	prob-nulo  CDATA #IMPLIED
>
<!ELEMENT asociar EMPTY>
<!ATTLIST asociar
	elemento  CDATA #REQUIRED
	generador CDATA #REQUIRED
	ruta      CDATA #REQUIRED
>
<!ELEMENT Importaciones (ruta)+>
<!ELEMENT ruta (#PCDATA)>

<!ELEMENT Parametros (cabecera)>
<!ELEMENT cabecera EMPTY>

<!-- Tabla -->
<!ELEMENT Tabla (Columnas, Restricciones)>
<!ATTLIST Tabla
	sp-campos CDATA #IMPLIED
	sp-filas  CDATA #IMPLIED
>

<!ELEMENT Columnas (cte | int | real | char | con | dis | sp | ref | ajena)+>
<!ATTLIST Columnas
	delim  CDATA #IMPLIED
	maxtam CDATA #IMPLIED
>

<!ELEMENT Restricciones (candidata | unica | no-nulo)*>
<!ELEMENT candidata (columna)+>
<!ELEMENT unica     (columna)+>
<!ELEMENT no-nulo   (columna)+>
<!ELEMENT columna   (#PCDATA)>

<!-- Generadores -->
<!ELEMENT cte (#PCDATA)>
<!ATTLIST cte
	id    CDATA #IMPLIED
>
<!ELEMENT int EMPTY>
<!ATTLIST int
	id    CDATA   #IMPLIED
	min   NMTOKEN #IMPLIED
	max   NMTOKEN #IMPLIED
	paso  NMTOKEN #IMPLIED
>
<!ELEMENT real EMPTY>
<!ATTLIST real
	id     CDATA   #IMPLIED
	min    NMTOKEN #IMPLIED
	max    NMTOKEN #IMPLIED
	paso   NMTOKEN #IMPLIED
	escala NMTOKEN #IMPLIED
>
<!ELEMENT char EMPTY>
<!ATTLIST char
	id    CDATA   #IMPLIED
	tipo  (M | m) #IMPLIED
>
<!ELEMENT con (cte | entero | real | char | con | dis | sp | ajena)*>
<!ATTLIST con
	id    CDATA #IMPLIED
>
<!ELEMENT dis (cte | entero | real | char | con | dis | sp | ajena)*>
<!ATTLIST dis
	id    CDATA #IMPLIED
>
<!ELEMENT sp EMPTY>
<!ATTLIST sp
	id    CDATA #IMPLIED
	val   CDATA #IMPLIED
>
<!ELEMENT ref EMPTY>
<!ATTLIST ref
	id  CDATA #IMPLIED
	gen CDATA #REQUIRED
>
<!ELEMENT ajena EMPTY>
<!ATTLIST ajena
	tabla       CDATA #REQUIRED
	delim-colum CDATA #IMPLIED
	sp-colum    CDATA #IMPLIED
	sp-filas    CDATA #IMPLIED
	nom-colum   CDATA #IMPLIED
	num-colum   CDATA #IMPLIED
>

=== jesuspv/ETLGen/lib/edificio.xml
<?xml version="1.0"?>
<!DOCTYPE Columnas SYSTEM "etc/ETL.dtd">
<Columnas>
	<dis id="edificio">
		<cte>Escuela Politecnica I</cte>
		<cte>Escuela Politecnica II</cte>
		<cte>Aulario I</cte>
		<cte>Aulario II</cte>
		<cte>Aulario III</cte>
		<cte>Aulario IV</cte>
		<cte>Aulario V</cte>
	</dis>
</Columnas>

=== jesuspv/ETLGen/data/provincia.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<ref id="PROV_ID" gen="ID" />
		<ref id="PROV_NOMBRE" gen="provincia" />
		<ajena id="FK_PROVINCIA_PAIS_NAC" tabla="pais" nom-colum="PAIS_ID" />
	</Columnas>
	<Restricciones>
		<candidata><columna>PROV_NOMBRE</columna></candidata>
		<candidata><columna>PROV_ID</columna></candidata>
		<no-nulo><columna>FK_PROVINCIA_PAIS_NAC</columna></no-nulo>
	</Restricciones>
</Tabla>

=== jesuspv/ETLGen/data/examen.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<dis id="EXA_CATEGORIA">
			<cte>Global</cte>
			<cte>Parcial</cte>
			<cte>Anual</cte>
			<cte>Cuatrimestral</cte>
		</dis>
		<dis id="EXA_DIFICULTAD">
			<cte>Muy Dificil</cte>
			<cte>Dificil</cte>
			<cte>Complejo</cte>
			<cte>Medio</cte>
			<cte>Facil</cte>
			<cte>Muy Facil</cte>
		</dis>
		<int id="EXA_DURACION" min="15" max="240" paso="15" />
		<con id="EXA_EXAMEN">
				<char tipo="M" />
				<char tipo="M" />
				<char tipo="M" />
				<ref gen="int2" />
				<ref gen="int2" />
		</con>
		<ref id="EXA_FECHA_ENTREGA_NOTAS" gen="fecha" />
		<ref id="EXA_FECHA_REVISION" gen="fecha" />
		<ref id="EXA_ID" gen="ID" />
		<int id="EXA_NUM_HOJAS" min="0" max="10" paso="1" />
		<int id="EXA_NUM_HORAS_ESTUDIADAS" min="0" max="100" paso="5" />
		<int id="EXA_NUM_PREGUNTAS_PRACTICAS" min="0" max="50" paso="1" />
		<int id="EXA_NUM_PREGUNTAS_TEORICAS" min="0" max="50" paso="1" />
		<int id="EXA_NUM_PROFESORES" min="1" max="9" paso="1" />
		<int id="EXA_NUM_TEMAS" min="1" max="30" paso="1" />
		<real id="EXA_PENALIZACION_ERROR" min="0.0" max="10.0" escala="2" paso="0.25" />
		<real id="EXA_PENALIZACION_NO_CONTESTADO" min="0.0" max="10.0" escala="2" paso="0.25" />
		<ref id="EXA_PORCENT_NOTA_ASIGNATURA" gen="porcentaje" />
		<ref id="EXA_PORCENT_PREGUNTA" gen="porcentaje" />
		<ref id="EXA_PORCENT_PREGUNTAS_TEORICAS" gen="porcentaje" />
		<ref id="EXA_PORCENT_PUNTOS_PRACTICOS" gen="porcentaje" />
		<ref id="EXA_PORCENT_PUNTOS_TEORICAS" gen="porcentaje" />
		<real id="EXA_PUNTUACION_MAX" min="0.0" max="10.0" escala="2" paso="0.25" />
		<real id="EXA_PUNTUACION_MED" min="0.0" max="10.0" escala="2" paso="0.25" />
		<real id="EXA_PUNTUACION_MIN" min="0.0" max="10.0" escala="2" paso="0.25" />
		<int id="EXA_TIEMPO_ESTIMADO_REALIZA" min="15" max="240" paso="15" />
		<dis id="EXA_TIPO">
			<cte>Practico</cte>
			<cte>Teorico</cte>
		</dis>
		<int id="PR1_ID" min="0" max="1000" paso="1" />
		<ref id="PR1_NOMBRE" gen="persona" />
		<int id="PR2_ID" min="0" max="1000" paso="1" />
		<ref id="PR2_NOMBRE" gen="persona" />
		<int id="PR3_ID" min="0" max="1000" paso="1" />
		<ref id="PR3_NOMBRE" gen="persona" />
	</Columnas>
	<Restricciones>
		<candidata><columna>EXA_EXAMEN</columna></candidata>
		<candidata><columna>EXA_ID</columna></candidata>
		<no-nulo><columna>PR1_ID</columna></no-nulo>
		<no-nulo><columna>PR2_ID</columna></no-nulo>
		<no-nulo><columna>PR3_ID</columna></no-nulo>
		<no-nulo><columna>PR1_NOMBRE</columna></no-nulo>
		<no-nulo><columna>PR2_NOMBRE</columna></no-nulo>
		<no-nulo><columna>PR3_NOMBRE</columna></no-nulo>
	</Restricciones>
</Tabla>

=== jesuspv/ETLGen/lib/email.xml
<?xml version="1.0"?>
<!DOCTYPE Columnas SYSTEM "etc/ETL.dtd">
<Columnas>
	<dis id="email">
		<cte>lorenzo.abad@ua.es</cte>
		<cte>juan.abascal@ua.es</cte>
		<cte>abasolo@fyl.uva.es</cte>
		<cte>museuhist@tinet.fut.es</cte>
		<cte>abreu@utad.pt</cte>
		<cte>phfacas@usc.es</cte>
		<cte>j.r.adams@soton.ac.uk</cte>
		<cte>dhajam0@clust.uib.es</cte>
		<cte>paguayo@ugr.es</cte>
		<cte>jerezmuseoarq@ctv.es</cte>
		<cte>gaguilella@dipcas.es</cte>
		<cte>aguilera@ceipac.gh.ub.es</cte>
		<cte>iarq@gemini.ci.uc.pt</cte>
		<cte>gabriel.alcalde@udg.es</cte>
		<cte>ealcorta@unav.es</cte>
		<cte>fgpalrua@vh.ehu.es</cte>
		<cte>jalejo@goliat.ugr.es</cte>
		<cte>calemany@fil.upoc.es</cte>
		<cte>caa@man.es</cte>
		<cte>falia@bibl-cr.uclm.es</cte>
		<cte>anticuario.rah@insde.es</cte>
		<cte>mavila@fyl.uva.es</cte>
		<cte>arqueologia@historia.udl.es</cte>
		<cte>aalonso@unex.es</cte>
		<cte>jalvar@uhu.es</cte>
		<cte>epanik@gugu.usal.es</cte>
		<cte>mnar@mnar.es</cte>
		<cte>jralvarez@inicia.es</cte> 
		<cte>jalvarez33@jazzfree.com</cte>
		<cte>phsusoa@usc.es</cte>
		<cte>fernando@polifemo.us.es</cte>
		<cte>tandres@posta.unizar.es</cte>
		<cte>cantonaccio@wesleyan.edu</cte>
		<cte>xaquilue@empuries.mac.es</cte>
		<cte>garanda@platon.ugr.es</cte>
		<cte>fjaranda@hist-cr.uclm.es</cte>
		<cte>carmen.aranegui@uv.es</cte>
		<cte>ferran.arasa@uv.es</cte>
		<cte>jarce@ceh.csic.es</cte>
		<cte>cardarco@ull.es</cte>
		<cte>alicia.arevalo@uca.es</cte>
	</dis>
</Columnas>

=== jesuspv/ETLGen/lib/nota.xml
<?xml version="1.0"?>
<!DOCTYPE Columnas SYSTEM "etc/ETL.dtd">
<Columnas>
	<dis id="nota">
		<cte>Suspenso</cte>
		<cte>No Presentado</cte>
		<cte>Aprobado</cte>
		<cte>Notable</cte>
		<cte>Sobresaliente</cte>
		<cte>Matricula de Honor</cte>
	</dis>
</Columnas>

=== jesuspv/ETLGen/etc/Config.xml
<?xml version="1.0"?>
<!DOCTYPE ETLConfig SYSTEM "etc/ETL.dtd">
<Configuracion>
	<Generadores valor-nulo="NULL" prob-nulo="0.15">
		<asociar elemento="cte" generador="etlgen.CteGenerador"
			ruta="C:\bdm\etlgen\bin\Debug\etlgen.exe" />
		<asociar elemento="int" generador="etlgen.IntGenerador"
			ruta="C:\bdm\etlgen\bin\Debug\etlgen.exe" />
		<asociar elemento="real" generador="etlgen.RealGenerador"
			ruta="C:\bdm\etlgen\bin\Debug\etlgen.exe" />
		<asociar elemento="char" generador="etlgen.CharGenerador"
			ruta="C:\bdm\etlgen\bin\Debug\etlgen.exe" />
		<asociar elemento="con" generador="etlgen.ConGenerador"
			ruta="C:\bdm\etlgen\bin\Debug\etlgen.exe" />
		<asociar elemento="dis" generador="etlgen.DisGenerador"
			ruta="C:\bdm\etlgen\bin\Debug\etlgen.exe" />
		<asociar elemento="sp" generador="etlgen.SpGenerador"
			ruta="C:\bdm\etlgen\bin\Debug\etlgen.exe" />
		<asociar elemento="ref" generador="etlgen.RefGenerador"
			ruta="C:\bdm\etlgen\bin\Debug\etlgen.exe" />
		<asociar elemento="ajena" generador="etlgen.AjenaGenerador"
			ruta="C:\bdm\etlgen\bin\Debug\etlgen.exe" />
		<asociar elemento="da_smart_key" generador="etlgen.FechaGenerador"
			ruta="C:\bdm\etlgen\bin\Debug\etlgen.exe" />
	</Generadores>
	<Importaciones>
		<ruta>C:\bdm\etlgen\lib</ruta>
	</Importaciones>
	<Parametros>
		<cabecera />
	</Parametros>
</Configuracion>

=== jesuspv/ETLGen/data/asistencia.xml
<?xml version="1.0"?>
<!DOCTYPE Tabla SYSTEM "etc/ETL.dtd">
<Tabla sp-campos=";" sp-filas="\r\n">
	<Columnas maxtam="50" delim="&quot;">
		<ajena id="FK_ASIGNATURA" tabla="asignatura" nom-colum="ASI_ID" />
		<ajena id="FK_AULA" tabla="aula" nom-colum="AUL_ID" />
		<da_smart_key id="FK_FECHA" file="C:\bdm\etlgen\ora\da_smart_key.txt" />
		<ajena id="FK_FRANJA_HORARIA" tabla="franjahoraria" nom-colum="FRH_ID" />
		<ajena id="FK_ALUMNO" tabla="matricula" nom-colum="MAT_ID" />
		<ajena id="FK_PROFESOR" tabla="profesor" nom-colum="PRO_ID" />
		<cte id="DUMMY">1</cte>
	</Columnas>
	<Restricciones>
		<candidata><columna>FK_ASIGNATURA</columna>
		           <columna>FK_AULA</columna>
		           <columna>FK_FECHA</columna>
		           <columna>FK_FRANJA_HORARIA</columna>
		           <columna>FK_ALUMNO</columna>
		           <columna>FK_PROFESOR</columna>
		</candidata>
		<no-nulo><columna>DUMMY</columna></no-nulo>
	</Restricciones>
</Tabla>

=== jesuspv/ETLGen/lib/asignatura.xml
<?xml version="1.0"?>
<!DOCTYPE Columnas SYSTEM "etc/ETL.dtd">
<Columnas>
	<dis id="asignatura">
		<cte>Algoritmia Avanzada</cte>
		<cte>Bases de Datos Avanzadas</cte>
		<cte>Bases de Datos Distribuidas</cte>
		<cte>Bases de Datos I</cte>
		<cte>Bases de Datos II</cte>
		<cte>Bases de Datos Multidimensionales</cte>
		<cte>Diseño de Sistemas Software</cte>
		<cte>Diseño y Análisis de Algoritmos</cte>
		<cte>Fundamentos de Programación II</cte>
		<cte>Herramientas de Programación</cte>
		<cte>Informática Musical</cte>
		<cte>Ingeniería del Lenguaje Natural</cte>
		<cte>Ingeniería del Software I</cte>
		<cte>Lenguajes, Gramáticas y Autómatas</cte>
		<cte>Procesadores de Lenguajes</cte>
		<cte>Programación Concurrente</cte>
		<cte>Programación en Entornos Interactivos</cte>
		<cte>Programación en Internet</cte>
		<cte>Programación Orientada a Objetos</cte>
		<cte>Programación y Estructuras de Datos</cte>
		<cte>Sistemas de Información Semiestructurada</cte>
		<cte>Aprendizaje</cte>
		<cte>Bases de Datos Avanzadas</cte>
		<cte>Compiladores I</cte>
		<cte>Compiladores II</cte>
		<cte>Diseño y Gestión de Bases de Datos</cte>
		<cte>Esquemas Algorítmicos</cte>
		<cte>Fundamentos de las Bases de Datos</cte>
		<cte>Fundamentos de Programación</cte>
		<cte>Ingeniería del Software I</cte>
		<cte>Lenguajes, Gramáticas y Autómatas</cte>
		<cte>Programación Concurrente</cte>
		<cte>Programación en Entornos Interactivos</cte>
		<cte>Programación Metódica</cte>
		<cte>Programación Orientada a Objetos</cte>
		<cte>Reconocimiento de Formas</cte>
		<cte>Sistemas Informáticos</cte>
		<cte>Sistemas Informáticos Distribuidos</cte>
		<cte>Teoría de la Complejidad</cte>
		<cte>Tipos Abstractos de Datos</cte>
	</dis>
</Columnas>
